### ISSUE TITLE
Wifi hotspot

### ISSUE THREAD

**Issue by nunocodex** [nunocodex/PixelExperience-Builds#12]

**Comment by nunocodex** [comment]
Without password working, with password not.

**Comment by nunocodex** [comment]
2.4ghz working, 5ghz not working

**Comment by r33int** [comment]
Works for me with password on 2.4 ghz. Logcats appreciated

**Comment by r33int** [comment]
Possible fix for hotspot: https://github.com/xiaomeme-whyred/device_xiaomi_whyred/commit/9e7e01222c0c86934c5a15aee31065827cc0a527

**Comment by nunocodex** [comment]
> Possible fix for hotspot: [xiaomeme-whyred/device_xiaomi_whyred@9e7e012](https://github.com/xiaomeme-whyred/device_xiaomi_whyred/commit/9e7e01222c0c86934c5a15aee31065827cc0a527)

We have already this so not fix it, I need to test with clean installation

**Comment by nunocodex** [comment]
Hotspot 2.4ghz tested and working, 5ghz still have issue

**Comment by nunocodex** [comment]
Announcement Regarding 5GHz Wi-Fi Hotspots (Band 1)

Hello Mi Fans,

5GHz Wi-Fi hotspots (band 1) will no longer be supported on our products in the following countries and regions due to the EU restrictions on the indoor use of 5Ghz bands 1 and 2.


1. 27 member states of the European Union:
Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden.

2. Countries and regions that recognize the CE marking:
Egypt, Hong Kong SAR (China), Singapore, Turkey, Ukraine.


The support of this functionality (if any) will be removed from the currently retailed devices in the coming software updates.


Thanks for your understanding.
Source: https://en.miui.com/thread-4944909-1-1.html
