### ISSUE TITLE
Signal strenght

### ISSUE THREAD

**Issue by nunocodex** [nunocodex/PixelExperience-Builds#13]
![image](https://user-images.githubusercontent.com/21750/66416102-6874e600-e9fd-11e9-8a9b-2f7b6ad6690c.png)

**Comment by r33int** [comment]
Source issue. PE has to merge the ignore RSSNR patch.

**Comment by nunocodex** [comment]
See: https://github.com/BeastRoms/platform_frameworks_base/commit/d9e5da552b8f2edf95b110597911ed73fbf54ad2

**Comment by nunocodex** [comment]
Finally merged to PE sources, added the overlay and thats fixed now.
