### ISSUE TITLE
Bluetooth stopped working 

### ISSUE THREAD

**Issue by aadhiar42** [nunocodex/PixelExperience-Builds#14]
After a while Bluetooth getting force closed.

**Comment by r33int** [comment]
Have you installed a custom kernel? Some kernels are known to break bluetooth...

**Comment by aadhiar42** [comment]
> Have you installed a custom kernel? Some kernels are known to break bluetooth...

Maybe that's why. I flashed Genom Q. But it worked after that for a while until a reboot.

**Comment by r33int** [comment]
Genom breaks bluetooth currently, stick with stock kernel for now.

**Comment by nunocodex** [comment]
I see on our pe beta group one genom with fix for bt, you can try it
