### ISSUE TITLE
Lockscreen User profile photo padding issue 

### ISSUE THREAD

**Issue by Ashnetn** [nunocodex/PixelExperience-Builds#19]
The user profile picture on Lockscreen is not displayed properly. It's 
![Screenshot_20191010-095310](https://user-images.githubusercontent.com/34261866/66561653-7fd7de80-eb77-11e9-9ca0-ada674baaa5a.png)
Padding should be corrected

**Comment by r33int** [comment]
Rom issue, not device related

**Comment by nunocodex** [comment]
> Rom issue, not device related
