### ISSUE TITLE
Error on installing via orangefox recovery 

### ISSUE THREAD

**Issue by LeFzULa** [nunocodex/PixelExperience-Builds#23]

**Comment by LeFzULa** [comment]
I tried to install this via orangefox recovery latest build with android 10 supported recovery. It shows some no.s error it said pls make sure that you install the right file. But i already downloaded the exact file.

**Comment by rahuld1998** [comment]
First Flash global firmware 10.3.6.0 
Then flash rom

**Comment by LeFzULa** [comment]
my system corrupted after i flash that firmware

**Comment by nunocodex** [comment]
> my system corrupted after i flash that firmware

don't flash the latests version, this builds have fastboot issue. Need to flash via fastboot a old dtbo.img

**Comment by LeFzULa** [comment]
I will back to the plus version.. maybe if the android 10 has official
build.
