### ISSUE TITLE
Pixel Setup in Progress (Post setup)

### ISSUE THREAD

**Issue by yvdjee** [nunocodex/PixelExperience-Builds#27]
After restoring the backup from google.

[logs.txt](https://github.com/nunocodex/PixelExperience-Builds/files/3723019/logs.txt)

![Screenshot_20191014-131029](https://user-images.githubusercontent.com/36464817/66730396-14965100-ee84-11e9-8fe2-b48afa05e99e.png)

![Screenshot_20191014-130656](https://user-images.githubusercontent.com/36464817/66730340-b2d5e700-ee83-11e9-889a-163e1b2573cb.png)

**Comment by nunocodex** [comment]
I make a clean install and all setup working fine without any fc, probably you done something wrong.

**Comment by nunocodex** [comment]
Sorry post, i need to do tomorrow with wifi, ill check.

**Comment by nunocodex** [comment]
Tested and working fine.
