### ISSUE TITLE
Pixel Launcher Crashes

### ISSUE THREAD

**Issue by ErikDeridder** [nunocodex/PixelExperience-Builds#30]
On latest Android 10 build (PixelExperience_lavender-10.0-20191013-1600-BETA-OFFICIAL ) the Pixel Launcher craches 2-3 times a day

It only seems to happen when i am on home screen and swiping up to see the open apps

I am using the Gesture navigation
![Screenshot_20191016-084909](https://user-images.githubusercontent.com/38832755/66897511-6f03ee80-eff7-11e9-87ed-5eae4d60b813.png)

**Comment by nunocodex** [comment]
> On latest Android 10 build (PixelExperience_lavender-10.0-20191013-1600-BETA-OFFICIAL ) the Pixel Launcher craches 2-3 times a day
> 
> It only seems to happen when i am on home screen and swiping up to see the open apps
> 
> I am using the Gesture navigation
> ![Screenshot_20191016-084909](https://user-images.githubusercontent.com/38832755/66897511-6f03ee80-eff7-11e9-87ed-5eae4d60b813.png)

You can give us the logcat about it?

**Comment by ErikDeridder** [comment]
It seems that the crash is gone since i updated the Pixel Launcher to the latest version from APK mirror. The Pixel Launcher version were you can swipe down in middle of screen to get the notifications. Will see how it goes and keep you up to date

**Comment by nunocodex** [comment]
> It seems that the crash is gone since i updated the Pixel Launcher to the latest version from APK mirror. The Pixel Launcher version were you can swipe down in middle of screen to get the notifications. Will see how it goes and keep you up to date

Don't give support for third party app in beta stage
