### ISSUE TITLE
Safetynet failing

### ISSUE THREAD

**Issue by r33int** [nunocodex/PixelExperience-Builds#7]

**Comment by nunocodex** [comment]
https://github.com/PixelExperience-Devices/device_xiaomi_lavender/commit/39b1dfb51e06ec71c05cd23aa4e2f1b217f15617

**Comment by nunocodex** [comment]
Confirmed by Henrique, Google break all roms (miui too) satefynet check.

**Comment by nunocodex** [comment]
Finally fixed, upload in the website nearly
