### ISSUE TITLE
GCam Slowmotion

### ISSUE THREAD

**Issue by r33int** [nunocodex/PixelExperience-Builds#8]
Fix: https://github.com/faham1997/android_device_xiaomi_lavender/commit/323b980e737b227e1744f6ee5df9d4b00d19be25

**Comment by nunocodex** [comment]
Fixed https://github.com/nunocodex/PixelExperience-Builds/releases/tag/PixelExperience_lavender-10.0-20191015-0916-BETA-OFFICIAL
